
package org.oasis.open.docs.wsn.bw_2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NotificationProducerService", targetNamespace = "http://docs.oasis-open.org/wsn/bw-2", wsdlLocation = "file:/home/ddmitry/temp/bw-2.wsdl")
public class NotificationProducerService
    extends Service
{

    private final static URL NOTIFICATIONPRODUCERSERVICE_WSDL_LOCATION;
    private final static WebServiceException NOTIFICATIONPRODUCERSERVICE_EXCEPTION;
    private final static QName NOTIFICATIONPRODUCERSERVICE_QNAME = new QName("http://docs.oasis-open.org/wsn/bw-2", "NotificationProducerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/ddmitry/temp/bw-2.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTIFICATIONPRODUCERSERVICE_WSDL_LOCATION = url;
        NOTIFICATIONPRODUCERSERVICE_EXCEPTION = e;
    }

    public NotificationProducerService() {
        super(__getWsdlLocation(), NOTIFICATIONPRODUCERSERVICE_QNAME);
    }

    public NotificationProducerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTIFICATIONPRODUCERSERVICE_QNAME, features);
    }

    public NotificationProducerService(URL wsdlLocation) {
        super(wsdlLocation, NOTIFICATIONPRODUCERSERVICE_QNAME);
    }

    public NotificationProducerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTIFICATIONPRODUCERSERVICE_QNAME, features);
    }

    public NotificationProducerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationProducerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NotificationProducer
     */
    @WebEndpoint(name = "NotificationProducerPort")
    public NotificationProducer getNotificationProducerPort() {
        return super.getPort(new QName("http://docs.oasis-open.org/wsn/bw-2", "NotificationProducerPort"), NotificationProducer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationProducer
     */
    @WebEndpoint(name = "NotificationProducerPort")
    public NotificationProducer getNotificationProducerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/wsn/bw-2", "NotificationProducerPort"), NotificationProducer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTIFICATIONPRODUCERSERVICE_EXCEPTION!= null) {
            throw NOTIFICATIONPRODUCERSERVICE_EXCEPTION;
        }
        return NOTIFICATIONPRODUCERSERVICE_WSDL_LOCATION;
    }

}
