
package org.oasis.open.docs.wsn.bw_2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import org.oasis.open.docs.wsn.b_2.GetCurrentMessage;
import org.oasis.open.docs.wsn.b_2.GetCurrentMessageResponse;
import org.oasis.open.docs.wsn.b_2.Subscribe;
import org.oasis.open.docs.wsn.b_2.SubscribeResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationProducer", targetNamespace = "http://docs.oasis-open.org/wsn/bw-2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.oasis.open.docs.wsn.b_2.ObjectFactory.class,
    org.oasis.open.docs.wsrf.bf_2.ObjectFactory.class,
    org.oasis.open.docs.wsn.t_1.ObjectFactory.class,
    org.oasis.open.docs.wsrf.r_2.ObjectFactory.class,
    org.w3._2005._08.addressing.ObjectFactory.class
})
public interface NotificationProducer {


    /**
     * 
     * @param subscribeRequest
     * @return
     *     returns org.oasis_open.docs.wsn.b_2.SubscribeResponse
     * @throws UnsupportedPolicyRequestFault
     * @throws TopicNotSupportedFault
     * @throws InvalidTopicExpressionFault
     * @throws TopicExpressionDialectUnknownFault
     * @throws ResourceUnknownFault
     * @throws UnacceptableInitialTerminationTimeFault
     * @throws InvalidProducerPropertiesExpressionFault
     * @throws InvalidMessageContentExpressionFault
     * @throws UnrecognizedPolicyRequestFault
     * @throws SubscribeCreationFailedFault
     * @throws NotifyMessageNotSupportedFault
     * @throws InvalidFilterFault
     */
    @WebMethod(operationName = "Subscribe", action = "http://docs.oasis-open.org/wsn/bw-2/Subscribe")
    @WebResult(name = "SubscribeResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "SubscribeResponse")
    public SubscribeResponse subscribe(
        @WebParam(name = "Subscribe", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "SubscribeRequest")
        Subscribe subscribeRequest)
        throws InvalidFilterFault, InvalidMessageContentExpressionFault, InvalidProducerPropertiesExpressionFault, InvalidTopicExpressionFault, NotifyMessageNotSupportedFault, ResourceUnknownFault, SubscribeCreationFailedFault, TopicExpressionDialectUnknownFault, TopicNotSupportedFault, UnacceptableInitialTerminationTimeFault, UnrecognizedPolicyRequestFault, UnsupportedPolicyRequestFault
    ;

    /**
     * 
     * @param getCurrentMessageRequest
     * @return
     *     returns org.oasis_open.docs.wsn.b_2.GetCurrentMessageResponse
     * @throws InvalidTopicExpressionFault
     * @throws TopicExpressionDialectUnknownFault
     * @throws TopicNotSupportedFault
     * @throws NoCurrentMessageOnTopicFault
     * @throws ResourceUnknownFault
     * @throws MultipleTopicsSpecifiedFault
     */
    @WebMethod(operationName = "GetCurrentMessage", action = "http://docs.oasis-open.org/wsn/bw-2/GetCurrentMessage")
    @WebResult(name = "GetCurrentMessageResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "GetCurrentMessageResponse")
    public GetCurrentMessageResponse getCurrentMessage(
        @WebParam(name = "GetCurrentMessage", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "GetCurrentMessageRequest")
        GetCurrentMessage getCurrentMessageRequest)
        throws InvalidTopicExpressionFault, MultipleTopicsSpecifiedFault, NoCurrentMessageOnTopicFault, ResourceUnknownFault, TopicExpressionDialectUnknownFault, TopicNotSupportedFault
    ;

}
