
package org.oasis.open.docs.wsn.bw_2;

import javax.xml.ws.WebFault;

import org.oasis.open.docs.wsn.b_2.SubscribeCreationFailedFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SubscribeCreationFailedFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class SubscribeCreationFailedFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SubscribeCreationFailedFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SubscribeCreationFailedFault(String message, SubscribeCreationFailedFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SubscribeCreationFailedFault(String message, SubscribeCreationFailedFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.SubscribeCreationFailedFaultType
     */
    public SubscribeCreationFailedFaultType getFaultInfo() {
        return faultInfo;
    }

}
