
package org.oasis.open.docs.wsn.bw_2;

import javax.xml.ws.WebFault;

import org.oasis.open.docs.wsn.b_2.TopicNotSupportedFaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "TopicNotSupportedFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class TopicNotSupportedFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TopicNotSupportedFaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TopicNotSupportedFault(String message, TopicNotSupportedFaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TopicNotSupportedFault(String message, TopicNotSupportedFaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.oasis_open.docs.wsn.b_2.TopicNotSupportedFaultType
     */
    public TopicNotSupportedFaultType getFaultInfo() {
        return faultInfo;
    }

}
